import type { Metadata } from "next";
import { Geist, Geist_Mono, Allura } from "next/font/google";
import "./globals.css";
import Background from '@/components/background' 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const allura = Allura({
  subsets: ['latin'],
  variable: '--font-allura', // Questa variabile deve corrispondere a quella nel CSS
  weight: '400',
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${allura.variable} antialiased`}
      >
        
        {children}
      </body>
    </html>
  );
}
